version: '3.8'

services:
  prestashop:
    build:
      context: .  # Directory where the Dockerfile is located
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - prestashop_data:/var/www/html
      - ./prestashop/files:/var/www/html  # Optional: Mount files for development
    environment:
      PS_DEV_MODE: 1          # Enable development mode
      DB_SERVER: db           # Database service name
      DB_USER: root
      DB_PASSWD: prestashop
      DB_NAME: prestashop

  db:
    image: mysql:5.7          # Use MySQL 5.7 for compatibility
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"           # MySQL default port

volumes:
  prestashop_data:
  db_data: