version: '3.8'

services:
  prestashop:
    build:
      context: .  # Directory where the Dockerfile is located
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - prestashop_data:/var/www/html/prestashop  # Persist PrestaShop data in a subdirectory
      - ./prestashop/files:/var/www/html  # Optional: Mount files for development
      - ./deployer:/var/www/html/deployer  # Mount the 'deployer' folder into the container
    environment:
      PS_DEV_MODE: 1           # Enable PrestaShop development mode
      DB_SERVER: db            # Database service name
      DB_USER: root            # MySQL user
      DB_PASSWD: prestashop    # MySQL password
      DB_NAME: prestashop      # MySQL database for PrestaShop

  db:
    image: mysql:5.7          # Use MySQL 5.7 for compatibility
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: prestashop  # MySQL root password
      MYSQL_DATABASE: prestashop      # Default PrestaShop database
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
    ports:
      - "3306:3306"             # MySQL default port

volumes:
  prestashop_data:  # Volume to persist PrestaShop data (like images, themes, etc.)
  db_data:          # Volume to persist MySQL database data
